package com.admin.ac.ding.model;

import javax.persistence.*;

@Table(name = "`carts`")
public class Carts extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.user_id
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.commodity_id
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carts.commodity_amount
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    private Integer commodityAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.user_id
     *
     * @return the value of carts.user_id
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.user_id
     *
     * @param userId the value for carts.user_id
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.commodity_id
     *
     * @return the value of carts.commodity_id
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.commodity_id
     *
     * @param commodityId the value for carts.commodity_id
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carts.commodity_amount
     *
     * @return the value of carts.commodity_amount
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    public Integer getCommodityAmount() {
        return commodityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carts.commodity_amount
     *
     * @param commodityAmount the value for carts.commodity_amount
     *
     * @mbg.generated Sun Oct 07 16:31:45 CST 2018
     */
    public void setCommodityAmount(Integer commodityAmount) {
        this.commodityAmount = commodityAmount;
    }
}