package com.admin.ac.ding.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "`commodity`")
public class Commodity extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_name
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private String commodityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_price
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private BigDecimal commodityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_spec
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private String commoditySpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_sales
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private Integer commoditySales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_id
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.hot_sales
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private Byte hotSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.category_id
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.on_sale
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private Byte onSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity_pics
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    private String commodityPics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_name
     *
     * @return the value of commodity.commodity_name
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_name
     *
     * @param commodityName the value for commodity.commodity_name
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_price
     *
     * @return the value of commodity.commodity_price
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public BigDecimal getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_price
     *
     * @param commodityPrice the value for commodity.commodity_price
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCommodityPrice(BigDecimal commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_spec
     *
     * @return the value of commodity.commodity_spec
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public String getCommoditySpec() {
        return commoditySpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_spec
     *
     * @param commoditySpec the value for commodity.commodity_spec
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCommoditySpec(String commoditySpec) {
        this.commoditySpec = commoditySpec == null ? null : commoditySpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_sales
     *
     * @return the value of commodity.commodity_sales
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public Integer getCommoditySales() {
        return commoditySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_sales
     *
     * @param commoditySales the value for commodity.commodity_sales
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCommoditySales(Integer commoditySales) {
        this.commoditySales = commoditySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_id
     *
     * @return the value of commodity.commodity_id
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_id
     *
     * @param commodityId the value for commodity.commodity_id
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.hot_sales
     *
     * @return the value of commodity.hot_sales
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public Byte getHotSales() {
        return hotSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.hot_sales
     *
     * @param hotSales the value for commodity.hot_sales
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setHotSales(Byte hotSales) {
        this.hotSales = hotSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category_id
     *
     * @return the value of commodity.category_id
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category_id
     *
     * @param categoryId the value for commodity.category_id
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.on_sale
     *
     * @return the value of commodity.on_sale
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public Byte getOnSale() {
        return onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.on_sale
     *
     * @param onSale the value for commodity.on_sale
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setOnSale(Byte onSale) {
        this.onSale = onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_pics
     *
     * @return the value of commodity.commodity_pics
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public String getCommodityPics() {
        return commodityPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_pics
     *
     * @param commodityPics the value for commodity.commodity_pics
     *
     * @mbg.generated Wed Oct 17 23:19:40 CST 2018
     */
    public void setCommodityPics(String commodityPics) {
        this.commodityPics = commodityPics == null ? null : commodityPics.trim();
    }
}