package com.admin.ac.ding.model;

import javax.persistence.*;

@Table(name = "`sys_role`")
public class SysRole extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.user_id
     *
     * @mbg.generated Thu Oct 18 22:25:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role
     *
     * @mbg.generated Thu Oct 18 22:25:52 CST 2018
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.user_id
     *
     * @return the value of sys_role.user_id
     *
     * @mbg.generated Thu Oct 18 22:25:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.user_id
     *
     * @param userId the value for sys_role.user_id
     *
     * @mbg.generated Thu Oct 18 22:25:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role
     *
     * @return the value of sys_role.role
     *
     * @mbg.generated Thu Oct 18 22:25:52 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role
     *
     * @param role the value for sys_role.role
     *
     * @mbg.generated Thu Oct 18 22:25:52 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}